version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: scooters
    ports:
      - "5432:5432"

  app1:
    build:
      context: ./LAB8
    environment:
      NODE_ID: app1
      PEERS: "app2:5000,app3:5000"
      EXTERNAL_PORT: "5001"
    ports:
      - "5001:5000"
    depends_on:
      - db

  app2:
    build:
      context: ./LAB8
    environment:
      NODE_ID: app2
      PEERS: "app1:5000,app3:5000"
      EXTERNAL_PORT: "5002"
    ports:
      - "5002:5000"
    depends_on:
      - db

  app3:
    build:
      context: ./LAB8
    environment:
      NODE_ID: app3
      PEERS: "app2:5000,app1:5000"
      EXTERNAL_PORT: "5003"
    ports:
      - "5003:5000"
    depends_on:
      - db

#  rabbitmq:
#    image: "rabbitmq:3-management"
#    ports:
#      - "15672:15672"
#      - "5672:5672"

#  producer:
#    build:
#      context: ./LAB7
#    environment:
#      RABBITMQ_HOST: rabbitmq
#    command: python ./producer.py
#    depends_on:
#      - rabbitmq
#
#  consumer:
#    build:
#      context: ./LAB7
#    environment:
#      RABBITMQ_HOST: rabbitmq
#      POSTGRES_HOST: db
#      POSTGRES_DB: scooters
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: adminpass
#    command: python ./consumer.py
#    depends_on:
#      - rabbitmq
#      - db
